#!/bin/sh

# Check setting of LM_HOME
if [ -z "$LM_HOME" ];  then
    echo "please set LM_HOME to the location of your LearningMaster installation" 1>&2
    exit 1
fi

# Jar-files from library.
LIBCLASSPATH=""
add_to_libclasspath () {
    JARFILES=`cd "$1" && ls *.jar 2>/dev/null`
    for i in ${JARFILES} ; do
	if [ -z "$LIBCLASSPATH" ] ; then
	    LIBCLASSPATH="$1/$i"
	else
	    LIBCLASSPATH="$LIBCLASSPATH:$1/$i"
	fi
    done
}

# Add the jar files in the Tweaker lib dir to the classpath.
add_to_libclasspath "${LM_HOME}"/support-libs

# And finally, run ...
exec java \
    -server -XX:+HeapDumpOnOutOfMemoryError \
    -classpath "$CLASSPATH:$LIBCLASSPATH" \
    -Dlog4j.configuration=file:"$LM_HOME"/log4j.properties \
     ibis.ipl.server.Server --events --port 5437
